name: alerta_vecinal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  url_launcher: ^6.2.4
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.1
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^18.0.1
  
  # Navigation
  go_router: ^12.1.3
  
  # UI
  cupertino_icons: ^1.0.2
  
  # Image & Location
  image_picker: ^1.1.2
  
  # Location & Maps
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  
  # Utils
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
